import { createContext, useContext, useState, useEffect, ReactNode } from 'react'
import type { Theme, LanguageCode, Notification, AppState } from '../types'

interface AppContextType extends AppState {
  setTheme: (theme: Theme) => void
  setLanguage: (language: LanguageCode) => void
  toggleSidebar: () => void
  addNotification: (notification: Omit<Notification, 'id' | 'createdAt'>) => void
  markNotificationRead: (id: string) => void
  clearNotifications: () => void
  t: (key: string) => string
}

const AppContext = createContext<AppContextType | undefined>(undefined)

const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    users: 'Users',
    accounts: 'Accounts',
    regions: 'Regions',
    districts: 'Districts',
    banks: 'Banks',
    currencies: 'Currencies',
    languages: 'Languages',
    complexes: 'Complexes',
    buildings: 'Buildings',
    floors: 'Floors',
    amenities: 'Amenities',
    amenityCategories: 'Amenity Categories',
    roomTypes: 'Room Types',
    meterTypes: 'Meter Types',
    meterTariffs: 'Meter Tariffs',
    categories: 'Categories',
    realEstateTypes: 'Real Estate Types',
    listingCategories: 'Listing Categories',
    renovations: 'Renovations',
    landCategories: 'Land Categories',
    productionTypes: 'Production Types',
    moderation: 'Moderation',
    settings: 'Settings',
    logout: 'Logout',
    login: 'Login',
    phoneNumber: 'Phone Number',
    phone: 'Phone',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    search: 'Search',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    actions: 'Actions',
    name: 'Name',
    code: 'Code',
    status: 'Status',
    createdAt: 'Created At',
    noData: 'No data available',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    blocked: 'Blocked',
    accept: 'Accept',
    reject: 'Reject',
    block: 'Block',
    main: 'Main',
    hierarchy: 'Hierarchy',
    propertyConfig: 'Property Config',
    serviceConfig: 'Service Config',
    system: 'System',
    profile: 'Profile',
    notifications: 'Notifications',
    theme: 'Theme',
    language: 'Language',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    totalProperties: 'Total Properties',
    occupancyRate: 'Occupancy Rate',
    rentCollected: 'Rent Collected',
    pendingMaintenance: 'Pending Maintenance',
    listings: 'Listings',
    realEstates: 'Real Estates',
    units: 'Units',
    deleteConfirm: 'Are you sure you want to delete this item?',
    deleteWarning: 'This action cannot be undone.',
    // Floor-specific
    floorNumber: 'Floor Number',
    building: 'Building',
    buildingTypes: 'Types',
    totalArea: 'Total Area',
    ceilingHeight: 'Ceiling Height',
    floorPlan: 'Floor Plan (URL)',
    floorPlanPlaceholder: 'Enter floor plan URL...',
    note: 'Note',
    notePlaceholder: 'Add any additional notes...',
    selectBuilding: 'Select Building',
    selectBuildingFirst: 'Please select a building to view its floors',
    item_created: 'Item created successfully',
    item_updated: 'Item updated successfully',
    item_deleted: 'Item deleted successfully',
    // Building-specific
    buildingNumber: 'Building Number',
    complex: 'Complex',
    region: 'Region',
    district: 'District',
    commercial: 'Commercial',
    living: 'Living',
    buildingType: 'Type',
    floorsCount: 'Floors Count',
    address: 'Address',
    addressPlaceholder: 'Enter address...',
    latitude: 'Latitude',
    longitude: 'Longitude',
    selectComplex: 'Select Complex',
    selectRegion: 'Select Region',
    selectDistrict: 'Select District',
    // Real Estate Type fields
    description: 'Description',
    iconUrl: 'Icon URL',
    showBuildingSuggestion: 'Building Suggestion',
    showFloorSuggestion: 'Floor Suggestion',
    canHaveUnits: 'Can Have Units',
    canHaveMeters: 'Can Have Meters',
    realEstateType: 'Real Estate Type',
    // Listing Category fields
    parentCategory: 'Parent Category',
    noParent: 'No Parent (Root Category)',
    icon: 'Icon',
    preview: 'Preview',
    // Moderation detail
    back: 'Back',
    viewDetails: 'View Details',
    confirmAccept: 'Confirm Approval',
    confirmAcceptMessage: 'Are you sure you want to approve this item? It will become publicly visible.',
    rejectReason: 'Reject with Reason',
    blockReason: 'Block with Reason',
    reasonPlaceholder: 'Enter reason...',
    cancelled: 'Cancelled',
    owner: 'Owner',
    reason: 'Reason',
    cadastralNumber: 'Cadastral Number',
    floorPlanView: 'Floor Plan',
    pricePerMonth: 'Price/Month',
    pricePerSqm: 'Price/m²',
    filterByStatus: 'Filter by Status',
    allStatuses: 'All Statuses',
    searchModeration: 'Search by name, address...',
    livingArea: 'Living Area',
    location: 'Location',
    propertyInfo: 'Property Info',
    images: 'Images',
    type: 'Type',
    room: 'Room',
    floor: 'Floor',
    noReason: 'No reason provided',
    accepted: 'Item approved successfully',
    rejectedMsg: 'Item rejected successfully',
    blockedMsg: 'Item blocked successfully',
    locationHierarchy: 'Location Hierarchy',
    order: 'Order',
  },
  uz: {
    dashboard: 'Boshqaruv paneli',
    users: 'Foydalanuvchilar',
    accounts: 'Hisoblar',
    regions: 'Viloyatlar',
    districts: 'Tumanlar',
    banks: 'Banklar',
    currencies: 'Valyutalar',
    languages: 'Tillar',
    complexes: 'Majmualar',
    buildings: 'Binolar',
    floors: 'Qavatlar',
    amenities: 'Qulayliklar',
    amenityCategories: 'Qulaylik kategoriyalari',
    roomTypes: 'Xona turlari',
    meterTypes: 'Hisoblagich turlari',
    meterTariffs: 'Hisoblagich tariflari',
    categories: 'Kategoriyalar',
    realEstateTypes: 'Ko\'chmas mulk turlari',
    listingCategories: 'E\'lon kategoriyalari',
    renovations: 'Ta\'mirlar',
    landCategories: 'Yer kategoriyalari',
    productionTypes: 'Ishlab chiqarish turlari',
    moderation: 'Moderatsiya',
    settings: 'Sozlamalar',
    logout: 'Chiqish',
    login: 'Kirish',
    phoneNumber: 'Telefon raqami',
    phone: 'Telefon',
    password: 'Parol',
    forgotPassword: 'Parolni unutdingizmi?',
    search: 'Qidirish',
    add: 'Qo\'shish',
    edit: 'Tahrirlash',
    delete: 'O\'chirish',
    save: 'Saqlash',
    cancel: 'Bekor qilish',
    confirm: 'Tasdiqlash',
    actions: 'Amallar',
    name: 'Nomi',
    code: 'Kod',
    status: 'Holat',
    createdAt: 'Yaratilgan sana',
    noData: 'Ma\'lumot mavjud emas',
    loading: 'Yuklanmoqda...',
    error: 'Xato',
    success: 'Muvaffaqiyat',
    pending: 'Kutilmoqda',
    approved: 'Tasdiqlangan',
    rejected: 'Rad etilgan',
    blocked: 'Bloklangan',
    accept: 'Qabul qilish',
    reject: 'Rad etish',
    block: 'Bloklash',
    main: 'Asosiy',
    hierarchy: 'Ierarxiya',
    propertyConfig: 'Mulk sozlamalari',
    serviceConfig: 'Xizmat sozlamalari',
    system: 'Tizim',
    profile: 'Profil',
    notifications: 'Bildirishnomalar',
    theme: 'Mavzu',
    language: 'Til',
    darkMode: 'Qorong\'i rejim',
    lightMode: 'Yorug\' rejim',
    totalProperties: 'Jami mulklar',
    occupancyRate: 'Bandlik darajasi',
    rentCollected: 'Yig\'ilgan ijara',
    pendingMaintenance: 'Kutilayotgan texnik xizmat',
    listings: 'E\'lonlar',
    realEstates: 'Ko\'chmas mulklar',
    units: 'Birliklar',
    deleteConfirm: 'Haqiqatan ham bu elementni o\'chirmoqchimisiz?',
    deleteWarning: 'Bu amalni qaytarib bo\'lmaydi.',
    // Floor-specific
    floorNumber: 'Qavat raqami',
    building: 'Bino',
    buildingTypes: 'Turlar',
    totalArea: 'Umumiy maydon',
    ceilingHeight: 'Shift balandligi',
    floorPlan: 'Qavat rejasi (URL)',
    floorPlanPlaceholder: 'Qavat rejasi URL manzilini kiriting...',
    note: 'Izoh',
    notePlaceholder: 'Qo\'shimcha izohlar qo\'shing...',
    selectBuilding: 'Binoni tanlang',
    selectBuildingFirst: 'Qavatlarni ko\'rish uchun binoni tanlang',
    item_created: 'Element muvaffaqiyatli yaratildi',
    item_updated: 'Element muvaffaqiyatli yangilandi',
    item_deleted: 'Element muvaffaqiyatli o\'chirildi',
    // Building-specific
    buildingNumber: 'Bino raqami',
    complex: 'Majmua',
    region: 'Viloyat',
    district: 'Tuman',
    commercial: 'Tijorat',
    living: 'Turar-joy',
    buildingType: 'Tur',
    floorsCount: 'Qavatlar soni',
    address: 'Manzil',
    addressPlaceholder: 'Manzilni kiriting...',
    latitude: 'Kenglik',
    longitude: 'Uzunlik',
    selectComplex: 'Majmuani tanlang',
    selectRegion: 'Viloyatni tanlang',
    selectDistrict: 'Tumanni tanlang',
    // Real Estate Type fields
    description: 'Tavsif',
    iconUrl: 'Belgi URL',
    showBuildingSuggestion: 'Bino taklifi',
    showFloorSuggestion: 'Qavat taklifi',
    canHaveUnits: 'Birliklar bo\'lishi mumkin',
    canHaveMeters: 'Hisoblagichlar bo\'lishi mumkin',
    realEstateType: 'Ko\'chmas mulk turi',
    // Listing Category fields
    parentCategory: 'Ota kategoriya',
    noParent: 'Ota yo\'q (Asosiy kategoriya)',
    icon: 'Belgi',
    preview: 'Ko\'rish',
    back: 'Orqaga',
    viewDetails: 'Batafsil ko\'rish',
    confirmAccept: 'Tasdiqlash',
    confirmAcceptMessage: 'Haqiqatan ham bu elementni tasdiqlashni xohlaysizmi? U hammaga ko\'rinadigan bo\'ladi.',
    rejectReason: 'Sababini ko\'rsatib rad etish',
    blockReason: 'Sababini ko\'rsatib bloklash',
    reasonPlaceholder: 'Sababni kiriting...',
    cancelled: 'Bekor qilingan',
    owner: 'Egasi',
    reason: 'Sabab',
    cadastralNumber: 'Kadastr raqami',
    floorPlanView: 'Qavat rejasi',
    pricePerMonth: 'Narx/Oy',
    pricePerSqm: 'Narx/m²',
    filterByStatus: 'Holat bo\'yicha filtrlash',
    allStatuses: 'Barcha holatlar',
    searchModeration: 'Nomi, manzili bo\'yicha qidirish...',
    livingArea: 'Yashash maydoni',
    location: 'Joylashuv',
    propertyInfo: 'Mulk ma\'lumotlari',
    images: 'Rasmlar',
    type: 'Tur',
    room: 'Xona',
    floor: 'Qavat',
    noReason: 'Sabab ko\'rsatilmagan',
    accepted: 'Element muvaffaqiyatli tasdiqlandi',
    rejectedMsg: 'Element muvaffaqiyatli rad etildi',
    blockedMsg: 'Element muvaffaqiyatli bloklandi',
    locationHierarchy: 'Joylashuv ierarxiyasi',
    order: 'Tartib',
  },
  ru: {
    dashboard: 'Панель управления',
    users: 'Пользователи',
    accounts: 'Аккаунты',
    regions: 'Регионы',
    districts: 'Районы',
    banks: 'Банки',
    currencies: 'Валюты',
    languages: 'Языки',
    complexes: 'Комплексы',
    buildings: 'Здания',
    floors: 'Этажи',
    amenities: 'Удобства',
    amenityCategories: 'Категории удобств',
    roomTypes: 'Типы комнат',
    meterTypes: 'Типы счетчиков',
    meterTariffs: 'Тарифы счетчиков',
    categories: 'Категории',
    realEstateTypes: 'Типы недвижимости',
    listingCategories: 'Категории объявлений',
    renovations: 'Ремонты',
    landCategories: 'Категории земли',
    productionTypes: 'Типы производства',
    moderation: 'Модерация',
    settings: 'Настройки',
    logout: 'Выход',
    login: 'Вход',
    phoneNumber: 'Номер телефона',
    phone: 'Телефон',
    password: 'Пароль',
    forgotPassword: 'Забыли пароль?',
    search: 'Поиск',
    add: 'Добавить',
    edit: 'Редактировать',
    delete: 'Удалить',
    save: 'Сохранить',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    actions: 'Действия',
    name: 'Название',
    code: 'Код',
    status: 'Статус',
    createdAt: 'Дата создания',
    noData: 'Нет данных',
    loading: 'Загрузка...',
    error: 'Ошибка',
    success: 'Успех',
    pending: 'Ожидание',
    approved: 'Одобрено',
    rejected: 'Отклонено',
    blocked: 'Заблокировано',
    accept: 'Принять',
    reject: 'Отклонить',
    block: 'Заблокировать',
    main: 'Главная',
    hierarchy: 'Иерархия',
    propertyConfig: 'Настройки недвижимости',
    serviceConfig: 'Настройки услуг',
    system: 'Система',
    profile: 'Профиль',
    notifications: 'Уведомления',
    theme: 'Тема',
    language: 'Язык',
    darkMode: 'Темный режим',
    lightMode: 'Светлый режим',
    totalProperties: 'Всего объектов',
    occupancyRate: 'Заполняемость',
    rentCollected: 'Собранная аренда',
    pendingMaintenance: 'Ожидающее обслуживание',
    listings: 'Объявления',
    realEstates: 'Недвижимость',
    units: 'Единицы',
    deleteConfirm: 'Вы уверены, что хотите удалить этот элемент?',
    deleteWarning: 'Это действие нельзя отменить.',
    // Floor-specific
    floorNumber: 'Номер этажа',
    building: 'Здание',
    buildingTypes: 'Типы',
    totalArea: 'Общая площадь',
    ceilingHeight: 'Высота потолка',
    floorPlan: 'План этажа (URL)',
    floorPlanPlaceholder: 'Введите URL плана этажа...',
    note: 'Примечание',
    notePlaceholder: 'Добавьте дополнительные примечания...',
    selectBuilding: 'Выберите здание',
    selectBuildingFirst: 'Пожалуйста, выберите здание для просмотра этажей',
    item_created: 'Элемент успешно создан',
    item_updated: 'Элемент успешно обновлен',
    item_deleted: 'Элемент успешно удален',
    // Building-specific
    buildingNumber: 'Номер здания',
    complex: 'Комплекс',
    region: 'Регион',
    district: 'Район',
    commercial: 'Коммерческий',
    living: 'Жилой',
    buildingType: 'Тип',
    floorsCount: 'Количество этажей',
    address: 'Адрес',
    addressPlaceholder: 'Введите адрес...',
    latitude: 'Широта',
    longitude: 'Долгота',
    selectComplex: 'Выберите комплекс',
    selectRegion: 'Выберите регион',
    selectDistrict: 'Выберите район',
    // Real Estate Type fields
    description: 'Описание',
    iconUrl: 'URL иконки',
    showBuildingSuggestion: 'Предложение здания',
    showFloorSuggestion: 'Предложение этажа',
    canHaveUnits: 'Может иметь единицы',
    canHaveMeters: 'Может иметь счётчики',
    realEstateType: 'Тип недвижимости',
    // Listing Category fields
    parentCategory: 'Родительская категория',
    noParent: 'Нет родителя (Корневая категория)',
    icon: 'Иконка',
    preview: 'Предпросмотр',
    back: 'Назад',
    viewDetails: 'Подробнее',
    confirmAccept: 'Подтвердить одобрение',
    confirmAcceptMessage: 'Вы уверены, что хотите одобрить этот элемент? Он станет публично доступным.',
    rejectReason: 'Отклонить с причиной',
    blockReason: 'Заблокировать с причиной',
    reasonPlaceholder: 'Введите причину...',
    cancelled: 'Отменено',
    owner: 'Владелец',
    reason: 'Причина',
    cadastralNumber: 'Кадастровый номер',
    floorPlanView: 'План этажа',
    pricePerMonth: 'Цена/Месяц',
    pricePerSqm: 'Цена/м²',
    filterByStatus: 'Фильтр по статусу',
    allStatuses: 'Все статусы',
    searchModeration: 'Поиск по названию, адресу...',
    livingArea: 'Жилая площадь',
    location: 'Расположение',
    propertyInfo: 'Информация об объекте',
    images: 'Изображения',
    type: 'Тип',
    room: 'Комната',
    floor: 'Этаж',
    noReason: 'Причина не указана',
    accepted: 'Элемент успешно одобрен',
    rejectedMsg: 'Элемент успешно отклонён',
    blockedMsg: 'Элемент успешно заблокирован',
    locationHierarchy: 'Иерархия расположения',
    order: 'Порядок',
  },
}

const getCookie = (name: string): string | null => {
  const match = document.cookie.match(new RegExp('(^| )' + name + '=([^;]+)'))
  return match ? match[2] : null
}

const setCookie = (name: string, value: string, days = 365) => {
  const expires = new Date(Date.now() + days * 864e5).toUTCString()
  document.cookie = `${name}=${value}; expires=${expires}; path=/`
}

export function AppProvider({ children }: { children: ReactNode }) {
  const [theme, setThemeState] = useState<Theme>(() => {
    const saved = localStorage.getItem('theme')
    return (saved as Theme) || 'light'
  })

  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = getCookie('lang')
    return (saved as LanguageCode) || 'en'
  })

  const [sidebarCollapsed, setSidebarCollapsed] = useState(false)
  const [notifications, setNotifications] = useState<Notification[]>([])

  useEffect(() => {
    localStorage.setItem('theme', theme)
    document.documentElement.classList.toggle('dark', theme === 'dark')
  }, [theme])

  useEffect(() => {
    setCookie('lang', language)
  }, [language])

  const setTheme = (newTheme: Theme) => setThemeState(newTheme)
  const setLanguage = (newLanguage: LanguageCode) => setLanguageState(newLanguage)
  const toggleSidebar = () => setSidebarCollapsed(prev => !prev)

  const addNotification = (notification: Omit<Notification, 'id' | 'createdAt'>) => {
    const newNotification: Notification = {
      ...notification,
      id: crypto.randomUUID(),
      createdAt: new Date().toISOString(),
    }
    setNotifications(prev => [newNotification, ...prev])
  }

  const markNotificationRead = (id: string) => {
    setNotifications(prev =>
      prev.map(n => (n.id === id ? { ...n, read: true } : n))
    )
  }

  const clearNotifications = () => setNotifications([])

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  return (
    <AppContext.Provider
      value={{
        theme,
        language,
        notifications,
        sidebarCollapsed,
        setTheme,
        setLanguage,
        toggleSidebar,
        addNotification,
        markNotificationRead,
        clearNotifications,
        t,
      }}
    >
      {children}
    </AppContext.Provider>
  )
}

export function useApp() {
  const context = useContext(AppContext)
  if (!context) {
    throw new Error('useApp must be used within AppProvider')
  }
  return context
}
