// <auto-generated />
using System;
using Document.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Document.Infrastructure.Migrations
{
    [DbContext(typeof(DocumentDbContext))]
    partial class DocumentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("documents")
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Document.Domain.ContractTemplates.ContractTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bodies")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bodies");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("current_version");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .HasColumnType("jsonb")
                        .HasColumnName("description");

                    b.Property<string>("Footer")
                        .HasColumnType("jsonb")
                        .HasColumnName("footer");

                    b.Property<string>("Header")
                        .HasColumnType("jsonb")
                        .HasColumnName("header");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ManualFields")
                        .HasColumnType("jsonb")
                        .HasColumnName("manual_fields");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("name");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("page");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("theme");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_contract_templates");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_contract_templates_category");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_contract_templates_code");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_contract_templates_created_by_user_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_contract_templates_is_active");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_contract_templates_scope");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contract_templates_tenant_id");

                    b.ToTable("contract_templates", "documents");
                });

            modelBuilder.Entity("Document.Domain.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("body");

                    b.Property<Guid?>("ClientCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_company_id");

                    b.Property<string>("ClientInn")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("client_inn");

                    b.Property<string>("ClientPinfl")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("client_pinfl");

                    b.Property<DateTime?>("ClientSignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_signed_at");

                    b.Property<DateTime>("ContractDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("contract_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contract_number");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<int>("CurrentVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("current_version");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("ExportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("exported_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<DateOnly?>("LeaseEndDate")
                        .HasColumnType("date")
                        .HasColumnName("lease_end_date");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<DateOnly>("LeaseStartDate")
                        .HasColumnType("date")
                        .HasColumnName("lease_start_date");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monthly_amount");

                    b.Property<Guid>("OwnerCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_company_id");

                    b.Property<string>("OwnerInn")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("owner_inn");

                    b.Property<string>("OwnerPinfl")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("owner_pinfl");

                    b.Property<DateTime?>("OwnerSignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("owner_signed_at");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<Guid>("RealEstateId")
                        .HasColumnType("uuid")
                        .HasColumnName("real_estate_id");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rejection_reason");

                    b.Property<DateTime?>("SignatureDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signature_deadline");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_contracts_created_by_user_id");

                    b.HasIndex("LeaseId")
                        .HasDatabaseName("ix_contracts_lease_id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_contracts_parent_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_contracts_status");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_contracts_template_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_contracts_tenant_id");

                    b.HasIndex("TenantId", "ContractNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_contracts_tenant_id_contract_number")
                        .HasFilter("contract_number IS NOT NULL");

                    b.ToTable("contracts", "documents");
                });

            modelBuilder.Entity("Document.Domain.Contracts.ContractAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("object_key");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_contract_attachments");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_attachments_contract_id");

                    b.ToTable("contract_attachments", "documents");
                });

            modelBuilder.Entity("Document.Domain.Contracts.ContractFinancialItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("frequency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_contract_financial_items");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_financial_items_contract_id");

                    b.ToTable("contract_financial_items", "documents");
                });

            modelBuilder.Entity("Document.Domain.Contracts.ContractSigningEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("ExternalSignatureId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_signature_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("party");

                    b.HasKey("Id")
                        .HasName("pk_contract_signing_events");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_contract_signing_events_contract_id");

                    b.ToTable("contract_signing_events", "documents");
                });

            modelBuilder.Entity("Document.Domain.Contracts.Contract", b =>
                {
                    b.HasOne("Document.Domain.Contracts.Contract", "Parent")
                        .WithMany("ChildContracts")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_contracts_contracts_parent_id");

                    b.OwnsMany("Document.Domain.Contracts.ContractProviderState", "IntegrationStates", b1 =>
                        {
                            b1.Property<Guid>("ContractId")
                                .HasColumnType("uuid")
                                .HasColumnName("contract_id");

                            b1.Property<string>("ProviderName")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("provider_name");

                            b1.Property<string>("ErrorMessage")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("error_message");

                            b1.Property<string>("ExternalId")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("external_id");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("last_updated");

                            b1.Property<string>("SyncStatus")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("sync_status");

                            b1.HasKey("ContractId", "ProviderName")
                                .HasName("pk_contract_provider_states");

                            b1.ToTable("contract_provider_states", "documents");

                            b1.WithOwner()
                                .HasForeignKey("ContractId")
                                .HasConstraintName("fk_contract_provider_states_contracts_contract_id");
                        });

                    b.Navigation("IntegrationStates");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Document.Domain.Contracts.ContractAttachment", b =>
                {
                    b.HasOne("Document.Domain.Contracts.Contract", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_attachments_contracts_contract_id");
                });

            modelBuilder.Entity("Document.Domain.Contracts.ContractFinancialItem", b =>
                {
                    b.HasOne("Document.Domain.Contracts.Contract", null)
                        .WithMany("FinancialItems")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_financial_items_contracts_contract_id");
                });

            modelBuilder.Entity("Document.Domain.Contracts.ContractSigningEvent", b =>
                {
                    b.HasOne("Document.Domain.Contracts.Contract", null)
                        .WithMany("SigningEvents")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_contract_signing_events_contracts_contract_id");
                });

            modelBuilder.Entity("Document.Domain.Contracts.Contract", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ChildContracts");

                    b.Navigation("FinancialItems");

                    b.Navigation("SigningEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
